org: arunpdl
app: products-sls
service: products-sls
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    DYNAMODB_PRODUCT_TABLE: ${self:service}-productTable-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-productTable-${sls:stage}
  httpApi:
    cors: true

functions:
  createProduct:
    handler: createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post
  getProducts:
    handler: getProducts.getProducts
    events:
      - httpApi:
          path: /products
          method: get
  deleteProduct:
    handler: deleteProduct.deleteProduct
    events:
      - httpApi:
          path: /products/{id}
          method: delete
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:service}-productTable-${sls:stage}
